/**
 * 完整导航树（对照 docs.expo.dev 侧边栏结构，2026-09）
 * 条目 slug 与官方 URL 路径一一对应；未翻译的页面由回退页兜底。
 */
export const nav = [
  {
    section: '首页',
    items: [{ slug: '', title: '文档首页', home: true }],
  },

  {
    section: '入门',
    items: [
      { slug: 'get-started/set-up-your-environment', title: '设置开发环境' },
      { slug: 'get-started/create-a-project', title: '创建项目' },
      { slug: 'get-started/start-developing', title: '开始开发' },
      { slug: 'get-started/next-steps', title: '下一步' },
    ],
  },

  {
    section: '开发',
    items: [
      { slug: 'develop/tools', title: '开发工具' },
      { slug: 'develop/unit-testing', title: '单元测试' },
      { slug: 'develop/app-navigation', title: '应用导航' },
      { slug: 'develop/authentication', title: '身份验证' },
      { slug: 'develop/database', title: '数据库' },
      {
        title: '开发构建',
        items: [
          { slug: 'develop/development-builds/introduction', title: '简介' },
          { slug: 'develop/development-builds/use-development-builds', title: '使用开发构建' },
          { slug: 'develop/development-builds/share-with-your-team', title: '与团队共享' },
          { slug: 'develop/development-builds/development-workflows', title: '开发工作流' },
          { slug: 'develop/development-builds/faq', title: '常见问题' },
        ],
      },
      {
        title: '用户界面',
        items: [
          { slug: 'develop/user-interface/splash-screen-and-app-icon', title: '启动屏与应用图标' },
          { slug: 'develop/user-interface/safe-areas', title: '安全区域' },
          { slug: 'develop/user-interface/system-bars', title: '系统栏' },
          { slug: 'develop/user-interface/fonts', title: '字体' },
          { slug: 'develop/user-interface/assets', title: '资源文件' },
          { slug: 'develop/user-interface/color-themes', title: '颜色主题' },
          { slug: 'develop/user-interface/animation', title: '动画' },
          { slug: 'develop/user-interface/store-data', title: '存储数据' },
          { slug: 'develop/user-interface/next-steps', title: '下一步' },
        ],
      },
      {
        title: '配置插件',
        items: [
          { slug: 'config-plugins/introduction', title: '简介' },
          { slug: 'config-plugins/plugins', title: '插件' },
          { slug: 'config-plugins/mods', title: '修改器' },
          { slug: 'config-plugins/dangerous-mods', title: '危险修改器' },
          { slug: 'config-plugins/development-for-libraries', title: '面向库开发者' },
          { slug: 'config-plugins/development-and-debugging', title: '开发与调试' },
          { slug: 'config-plugins/patch-project', title: '修补项目' },
        ],
      },
      {
        title: '调试',
        items: [
          { slug: 'debugging/errors-and-warnings', title: '错误与警告' },
          { slug: 'debugging/runtime-issues', title: '运行时问题' },
          { slug: 'debugging/tools', title: '调试工具' },
          { slug: 'debugging/devtools-plugins', title: 'DevTools 插件' },
          { slug: 'debugging/create-devtools-plugins', title: '创建 DevTools 插件' },
        ],
      },
    ],
  },

  {
    section: '审查',
    items: [
      { slug: 'review/overview', title: '概览' },
      { slug: 'review/share-previews-with-your-team', title: '与团队共享预览' },
      { slug: 'review/with-orbit', title: '使用 Orbit' },
    ],
  },

  {
    section: '部署',
    items: [
      { slug: 'deploy/build-project', title: '构建项目' },
      { slug: 'deploy/submit-to-app-stores', title: '提交到应用商店' },
      { slug: 'deploy/app-stores-metadata', title: '应用商店元数据' },
      { slug: 'deploy/send-over-the-air-updates', title: '发送 OTA 更新' },
      { slug: 'deploy/web', title: '部署到 Web' },
    ],
  },

  {
    section: '指南',
    items: [
      { slug: 'guides/overview', title: '概览' },
      { slug: 'guides/apple-privacy', title: 'Apple 隐私清单' },
      { slug: 'guides/permissions', title: '权限' },
      { slug: 'guides/environment-variables', title: '环境变量' },
      { slug: 'guides/adopting-prebuild', title: '采用 Prebuild' },
      { slug: 'guides/local-app-overview', title: '本地优先应用概览' },
      { slug: 'guides/local-app-development', title: '本地优先应用开发' },
      { slug: 'guides/local-app-production', title: '本地优先应用生产部署' },
      { slug: 'guides/cache-builds-remotely', title: '远程缓存构建' },
      { slug: 'guides/prebuilt-expo-modules', title: '预构建 Expo 模块' },
      { slug: 'guides/publishing-websites', title: '发布网站' },
      { slug: 'guides/dom-components', title: 'DOM 组件' },
      { slug: 'guides/server-components', title: '服务端组件' },
      { slug: 'guides/testing-rsc', title: '测试 RSC' },
      { slug: 'guides/progressive-web-apps', title: '渐进式 Web 应用 (PWA)' },
      { slug: 'guides/tailwind', title: 'Tailwind CSS' },
      { slug: 'guides/local-https-development', title: '本地 HTTPS 开发' },
      { slug: 'guides/customizing-metro', title: '自定义 Metro' },
      { slug: 'guides/analyzing-bundles', title: '分析打包产物' },
      { slug: 'guides/tree-shaking', title: 'Tree Shaking' },
      { slug: 'guides/minify', title: '压缩' },
      { slug: 'guides/why-metro', title: '为什么使用 Metro' },
      { slug: 'guides/monorepos', title: 'Monorepo' },
      { slug: 'guides/new-architecture', title: '新架构' },
      { slug: 'guides/react-compiler', title: 'React Compiler' },
      { slug: 'guides/using-analytics', title: '使用 Analytics' },
      { slug: 'guides/using-sentry', title: '使用 Sentry' },
      { slug: 'guides/using-bugsnag', title: '使用 Bugsnag' },
      { slug: 'guides/using-logrocket', title: '使用 LogRocket' },
      {
        title: '使用 PostHog',
        items: [
          { slug: 'guides/using-posthog', title: '使用 PostHog' },
          { slug: 'guides/using-posthog/recipes', title: '配方' },
        ],
      },
      { slug: 'guides/using-authentication', title: '使用身份验证' },
      { slug: 'guides/using-clerk', title: '使用 Clerk' },
      { slug: 'guides/facebook-authentication', title: 'Facebook 登录' },
      { slug: 'guides/google-authentication', title: 'Google 登录' },
      { slug: 'guides/using-a-cms', title: '使用 CMS' },
      { slug: 'guides/using-convex', title: '使用 Convex' },
      { slug: 'guides/using-firebase', title: '使用 Firebase' },
      { slug: 'guides/using-supabase', title: '使用 Supabase' },
      { slug: 'guides/using-resend', title: '使用 Resend' },
      { slug: 'guides/using-feature-flags', title: '使用功能开关' },
      { slug: 'guides/in-app-purchases', title: '应用内购买' },
      { slug: 'guides/using-push-notifications-services', title: '使用推送通知服务' },
      { slug: 'guides/using-eslint', title: '使用 ESLint' },
      { slug: 'guides/typescript', title: 'TypeScript' },
      { slug: 'guides/building-for-tv', title: '构建 TV 应用' },
      { slug: 'guides/using-nextjs', title: '使用 Next.js' },
      {
        title: 'SDK 库迁移',
        items: [
          { slug: 'guides/sdk-libraries-migration/media-library', title: '媒体库' },
          { slug: 'guides/sdk-libraries-migration/calendar', title: '日历' },
          { slug: 'guides/sdk-libraries-migration/contacts', title: '联系人' },
        ],
      },
      { slug: 'guides/authentication', title: '身份验证' },
      { slug: 'guides/using-hermes', title: '使用 Hermes' },
      { slug: 'guides/ios-developer-mode', title: 'iOS 开发者模式' },
      { slug: 'guides/icons', title: '图标' },
      { slug: 'guides/localization', title: '本地化' },
      { slug: 'guides/using-bun', title: '使用 Bun' },
      { slug: 'guides/editing-richtext', title: '富文本编辑' },
      { slug: 'guides/store-assets', title: '商店资源' },
      { slug: 'guides/local-first', title: '本地优先' },
      { slug: 'guides/keyboard-handling', title: '键盘处理' },
      { slug: 'guides/controlled-components', title: '受控组件' },
    ],
  },

  {
    section: '参考',
    items: [
      {
        title: '深层链接',
        items: [
          { slug: 'linking/overview', title: '概览' },
          { slug: 'linking/into-other-apps', title: '链接到其他应用' },
          { slug: 'linking/into-your-app', title: '链接到你的应用' },
          { slug: 'linking/android-app-links', title: 'Android 应用链接' },
          { slug: 'linking/ios-universal-links', title: 'iOS 通用链接' },
        ],
      },
      {
        title: 'Expo 模块',
        items: [
          { slug: 'modules/overview', title: '概览' },
          { slug: 'modules/get-started', title: '快速开始' },
          { slug: 'modules/native-module-tutorial', title: '原生模块教程' },
          { slug: 'modules/native-view-tutorial', title: '原生视图教程' },
          { slug: 'modules/inline-modules-tutorial', title: '内联模块教程' },
          { slug: 'modules/type-generation-tutorial', title: '类型生成教程' },
          { slug: 'modules/config-plugin-and-native-module-tutorial', title: '配置插件与原生模块' },
          { slug: 'modules/use-standalone-expo-module-in-your-project', title: '在项目中使用独立模块' },
          { slug: 'modules/third-party-library', title: '第三方库' },
          { slug: 'modules/existing-library', title: '现有库' },
          { slug: 'modules/additional-platform-support', title: '额外平台支持' },
          { slug: 'modules/module-api', title: '模块 API' },
          { slug: 'modules/inline-modules-reference', title: '内联模块参考' },
          { slug: 'modules/type-generation-reference', title: '类型生成参考' },
          { slug: 'modules/android-lifecycle-listeners', title: 'Android 生命周期监听器' },
          { slug: 'modules/appdelegate-subscribers', title: 'AppDelegate 订阅者' },
          { slug: 'modules/autolinking', title: '自动链接' },
          { slug: 'modules/shared-objects', title: '共享对象' },
          { slug: 'modules/module-config', title: '模块配置' },
          { slug: 'modules/mocking', title: '模拟 (Mocking)' },
          { slug: 'modules/design', title: '设计' },
        ],
      },
      {
        title: '推送通知',
        items: [
          { slug: 'push-notifications/overview', title: '概览' },
          { slug: 'push-notifications/what-you-need-to-know', title: '你需要了解的' },
          { slug: 'push-notifications/push-notifications-setup', title: '推送通知设置' },
          { slug: 'push-notifications/sending-notifications', title: '发送通知' },
          { slug: 'push-notifications/receiving-notifications', title: '接收通知' },
          { slug: 'push-notifications/fcm-credentials', title: 'FCM 凭据' },
          { slug: 'push-notifications/sending-notifications-custom', title: '自定义发送通知' },
          { slug: 'push-notifications/faq', title: '常见问题' },
        ],
      },
      {
        title: '合规',
        items: [
          { slug: 'regulatory-compliance/data-and-privacy-protection', title: '数据与隐私保护' },
          { slug: 'regulatory-compliance/gdpr', title: 'GDPR' },
          { slug: 'regulatory-compliance/hipaa', title: 'HIPAA' },
        ],
      },
      {
        title: '疑难排查',
        items: [
          { slug: 'troubleshooting/overview', title: '概览' },
          { slug: 'troubleshooting/application-has-not-been-registered', title: '应用未注册错误' },
          { slug: 'troubleshooting/clear-cache-macos-linux', title: '清除缓存 (macOS/Linux)' },
          { slug: 'troubleshooting/clear-cache-windows', title: '清除缓存 (Windows)' },
          { slug: 'troubleshooting/expo-go-version-mismatch', title: 'Expo Go 版本不匹配' },
          { slug: 'troubleshooting/expo-go-sign-in-required', title: 'Expo Go 需要登录' },
          { slug: 'troubleshooting/react-native-version-mismatch', title: 'React Native 版本不匹配' },
          { slug: 'troubleshooting/proxies', title: '代理' },
        ],
      },
    ],
  },

  {
    section: 'Expo SDK',
    items: [
      { slug: 'versions/latest', title: 'SDK 概览', home: true },
      {
        title: '配置文件参考',
        items: [
          { slug: 'versions/latest/config/app', title: 'app.json / app.config.js' },
          { slug: 'versions/latest/config/babel', title: 'babel.config.js' },
          { slug: 'versions/latest/config/metro', title: 'metro.config.js' },
          { slug: 'versions/latest/config/package-json', title: 'package.json' },
        ],
      },
      {
        title: 'Expo Router 参考',
        items: [
          { slug: 'versions/latest/sdk/router', title: '概览' },
          { slug: 'versions/latest/sdk/router/color', title: 'Color' },
          { slug: 'versions/latest/sdk/router/experimental-stack', title: 'Experimental Stack' },
          { slug: 'versions/latest/sdk/router/link', title: 'Link' },
          { slug: 'versions/latest/sdk/router/native-tabs', title: 'Native tabs' },
          { slug: 'versions/latest/sdk/router/split-view', title: 'Split View' },
          { slug: 'versions/latest/sdk/router/stack', title: 'Stack' },
          { slug: 'versions/latest/sdk/router/ui', title: 'UI' },
        ],
      },
      {
        title: 'Expo UI',
        items: [
          { slug: 'versions/latest/sdk/ui', title: '概览' },
          { slug: 'versions/latest/sdk/ui/jetpack-compose', title: 'Jetpack Compose 组件' },
          { slug: 'versions/latest/sdk/ui/swift-ui', title: 'SwiftUI 组件' },
          { slug: 'versions/latest/sdk/ui/drop-in-replacements', title: 'Drop-in 替代组件' },
          { slug: 'versions/latest/sdk/ui/universal', title: '通用组件' },
        ],
      },
      {
        title: 'Expo SDK 包',
        items: [
          { slug: 'versions/latest/sdk/expo', title: 'expo' },
          { slug: 'versions/latest/sdk/accelerometer', title: 'expo-accelerometer' },
          { slug: 'versions/latest/sdk/age-range', title: 'expo-age-range' },
          { slug: 'versions/latest/sdk/app-integrity', title: 'expo-app-integrity' },
          { slug: 'versions/latest/sdk/apple-authentication', title: 'expo-apple-authentication' },
          { slug: 'versions/latest/sdk/application', title: 'expo-application' },
          { slug: 'versions/latest/sdk/asset', title: 'expo-asset' },
          { slug: 'versions/latest/sdk/audio', title: 'expo-audio' },
          { slug: 'versions/latest/sdk/auth-session', title: 'expo-auth-session' },
          { slug: 'versions/latest/sdk/background-fetch', title: 'expo-background-fetch' },
          { slug: 'versions/latest/sdk/background-task', title: 'expo-background-task' },
          { slug: 'versions/latest/sdk/barometer', title: 'expo-barometer' },
          { slug: 'versions/latest/sdk/battery', title: 'expo-battery' },
          { slug: 'versions/latest/sdk/blob', title: 'expo-blob' },
          { slug: 'versions/latest/sdk/blur-view', title: 'expo-blur-view' },
          { slug: 'versions/latest/sdk/brightness', title: 'expo-brightness' },
          { slug: 'versions/latest/sdk/brownfield', title: 'expo-brownfield' },
          { slug: 'versions/latest/sdk/build-properties', title: 'expo-build-properties' },
          { slug: 'versions/latest/sdk/calendar', title: 'expo-calendar' },
          { slug: 'versions/latest/sdk/calendar-legacy', title: 'expo-calendar-legacy' },
          { slug: 'versions/latest/sdk/camera', title: 'expo-camera' },
          { slug: 'versions/latest/sdk/cellular', title: 'expo-cellular' },
          { slug: 'versions/latest/sdk/checkbox', title: 'expo-checkbox' },
          { slug: 'versions/latest/sdk/clipboard', title: 'expo-clipboard' },
          { slug: 'versions/latest/sdk/constants', title: 'expo-constants' },
          { slug: 'versions/latest/sdk/contacts', title: 'expo-contacts' },
          { slug: 'versions/latest/sdk/contacts-legacy', title: 'expo-contacts-legacy' },
          { slug: 'versions/latest/sdk/crypto', title: 'expo-crypto' },
          { slug: 'versions/latest/sdk/dev-client', title: 'expo-dev-client' },
          { slug: 'versions/latest/sdk/device', title: 'expo-device' },
          { slug: 'versions/latest/sdk/devicemotion', title: 'expo-devicemotion' },
          { slug: 'versions/latest/sdk/dev-menu', title: 'expo-dev-menu' },
          { slug: 'versions/latest/sdk/document-picker', title: 'expo-document-picker' },
          { slug: 'versions/latest/sdk/filesystem', title: 'expo-file-system' },
          { slug: 'versions/latest/sdk/filesystem-legacy', title: 'expo-file-system-legacy' },
          { slug: 'versions/latest/sdk/fingerprint', title: 'expo-fingerprint' },
          { slug: 'versions/latest/sdk/font', title: 'expo-font' },
          { slug: 'versions/latest/sdk/glass-effect', title: 'expo-glass-effect' },
          { slug: 'versions/latest/sdk/gl-view', title: 'expo-gl-view' },
          { slug: 'versions/latest/sdk/gyroscope', title: 'expo-gyroscope' },
          { slug: 'versions/latest/sdk/haptics', title: 'expo-haptics' },
          { slug: 'versions/latest/sdk/image', title: 'expo-image' },
          { slug: 'versions/latest/sdk/imagemanipulator', title: 'expo-image-manipulator' },
          { slug: 'versions/latest/sdk/imagepicker', title: 'expo-image-picker' },
          { slug: 'versions/latest/sdk/intent-launcher', title: 'expo-intent-launcher' },
          { slug: 'versions/latest/sdk/keep-awake', title: 'expo-keep-awake' },
          { slug: 'versions/latest/sdk/light-sensor', title: 'expo-light-sensor' },
          { slug: 'versions/latest/sdk/linear-gradient', title: 'expo-linear-gradient' },
          { slug: 'versions/latest/sdk/linking', title: 'expo-linking' },
          { slug: 'versions/latest/sdk/live-photo', title: 'expo-live-photo' },
          { slug: 'versions/latest/sdk/local-authentication', title: 'expo-local-authentication' },
          { slug: 'versions/latest/sdk/localization', title: 'expo-localization' },
          { slug: 'versions/latest/sdk/location', title: 'expo-location' },
          { slug: 'versions/latest/sdk/magnetometer', title: 'expo-magnetometer' },
          { slug: 'versions/latest/sdk/mail-composer', title: 'expo-mail-composer' },
          { slug: 'versions/latest/sdk/manifests', title: 'expo-manifests' },
          { slug: 'versions/latest/sdk/maps', title: 'expo-maps' },
          { slug: 'versions/latest/sdk/media-library', title: 'expo-media-library' },
          { slug: 'versions/latest/sdk/media-library-legacy', title: 'expo-media-library-legacy' },
          { slug: 'versions/latest/sdk/mesh-gradient', title: 'expo-mesh-gradient' },
          { slug: 'versions/latest/sdk/navigation-bar', title: 'expo-navigation-bar' },
          { slug: 'versions/latest/sdk/network', title: 'expo-network' },
          { slug: 'versions/latest/sdk/notifications', title: 'expo-notifications' },
          { slug: 'versions/latest/sdk/observe', title: 'expo-observe' },
          { slug: 'versions/latest/sdk/pedometer', title: 'expo-pedometer' },
          { slug: 'versions/latest/sdk/print', title: 'expo-print' },
          { slug: 'versions/latest/sdk/screen-capture', title: 'expo-screen-capture' },
          { slug: 'versions/latest/sdk/screen-orientation', title: 'expo-screen-orientation' },
          { slug: 'versions/latest/sdk/securestore', title: 'expo-secure-store' },
          { slug: 'versions/latest/sdk/sensors', title: 'expo-sensors' },
          { slug: 'versions/latest/sdk/server', title: 'expo-server' },
          { slug: 'versions/latest/sdk/sharing', title: 'expo-sharing' },
          { slug: 'versions/latest/sdk/sms', title: 'expo-sms' },
          { slug: 'versions/latest/sdk/speech', title: 'expo-speech' },
          { slug: 'versions/latest/sdk/splash-screen', title: 'expo-splash-screen' },
          { slug: 'versions/latest/sdk/sqlite', title: 'expo-sqlite' },
          { slug: 'versions/latest/sdk/status-bar', title: 'expo-status-bar' },
          { slug: 'versions/latest/sdk/storereview', title: 'expo-store-review' },
          { slug: 'versions/latest/sdk/symbols', title: 'expo-symbols' },
          { slug: 'versions/latest/sdk/system-ui', title: 'expo-system-ui' },
          { slug: 'versions/latest/sdk/task-manager', title: 'expo-task-manager' },
          { slug: 'versions/latest/sdk/tracking-transparency', title: 'expo-tracking-transparency' },
          { slug: 'versions/latest/sdk/updates', title: 'expo-updates' },
          { slug: 'versions/latest/sdk/video', title: 'expo-video' },
          { slug: 'versions/latest/sdk/video-thumbnails', title: 'expo-video-thumbnails' },
          { slug: 'versions/latest/sdk/webbrowser', title: 'expo-web-browser' },
          { slug: 'versions/latest/sdk/widgets', title: 'expo-widgets' },
        ],
      },
      {
        title: '第三方库',
        items: [
          { slug: 'versions/latest/sdk/third-party-overview', title: '第三方库概览' },
          { slug: 'versions/latest/sdk/async-storage', title: '@react-native-async-storage/async-storage' },
          { slug: 'versions/latest/sdk/date-time-picker', title: '@react-native-community/datetimepicker' },
          { slug: 'versions/latest/sdk/netinfo', title: '@react-native-community/netinfo' },
          { slug: 'versions/latest/sdk/slider', title: '@react-native-community/slider' },
          { slug: 'versions/latest/sdk/masked-view', title: '@react-native-masked-view/masked-view' },
          { slug: 'versions/latest/sdk/picker', title: '@react-native-picker/picker' },
          { slug: 'versions/latest/sdk/segmented-control', title: '@react-native-segmented-control/segmented-control' },
          { slug: 'versions/latest/sdk/flash-list', title: '@shopify/flash-list' },
          { slug: 'versions/latest/sdk/skia', title: '@shopify/react-native-skia' },
          { slug: 'versions/latest/sdk/stripe', title: '@stripe/stripe-react-native' },
          { slug: 'versions/latest/sdk/gesture-handler', title: 'react-native-gesture-handler' },
          { slug: 'versions/latest/sdk/keyboard-controller', title: 'react-native-keyboard-controller' },
          { slug: 'versions/latest/sdk/map-view', title: 'react-native-maps' },
          { slug: 'versions/latest/sdk/view-pager', title: 'react-native-pager-view' },
          { slug: 'versions/latest/sdk/reanimated', title: 'react-native-reanimated' },
          { slug: 'versions/latest/sdk/safe-area-context', title: 'react-native-safe-area-context' },
          { slug: 'versions/latest/sdk/screens', title: 'react-native-screens' },
          { slug: 'versions/latest/sdk/svg', title: 'react-native-svg' },
          { slug: 'versions/latest/sdk/captureRef', title: 'react-native-view-shot' },
          { slug: 'versions/latest/sdk/webview', title: 'react-native-webview' },
        ],
      },
      {
        title: '技术规范',
        items: [
          { slug: 'technical-specs/expo-updates-1', title: 'Expo Updates v1' },
          { slug: 'technical-specs/expo-sfv-0', title: 'Expo 结构化字段值 (SFV)' },
        ],
      },
    ],
  },

  {
    section: 'Expo Router',
    items: [
      { slug: 'router/introduction', title: '简介' },
      { slug: 'router/installation', title: '安装' },
      {
        title: '基础',
        items: [
          { slug: 'router/basics/core-concepts', title: '核心概念' },
          { slug: 'router/basics/notation', title: '路由记法' },
          { slug: 'router/basics/navigation-layouts', title: '导航布局' },
          { slug: 'router/basics/navigation', title: '导航' },
          { slug: 'router/basics/common-navigation-patterns', title: '常见导航模式' },
        ],
      },
      {
        title: '进阶',
        items: [
          { slug: 'router/advanced/stack', title: '堆栈导航' },
          { slug: 'router/advanced/tabs', title: '标签页导航' },
          { slug: 'router/advanced/native-tabs', title: '原生标签页' },
          { slug: 'router/advanced/drawer', title: '抽屉导航' },
          { slug: 'router/advanced/authentication', title: '身份验证' },
          { slug: 'router/advanced/authentication-rewrites', title: '身份验证重写' },
          { slug: 'router/advanced/nesting-navigators', title: '嵌套导航器' },
          { slug: 'router/advanced/modals', title: '模态框' },
          { slug: 'router/advanced/web-modals', title: 'Web 模态框' },
          { slug: 'router/advanced/shared-routes', title: '共享路由' },
          { slug: 'router/advanced/protected', title: '受保护路由' },
          { slug: 'router/advanced/prevent-screen-removal', title: '防止移除页面' },
          { slug: 'router/advanced/platform-specific-modules', title: '平台特定模块' },
          { slug: 'router/advanced/native-intent', title: '原生 Intent' },
          { slug: 'router/advanced/router-settings', title: '路由设置' },
          { slug: 'router/advanced/apple-handoff', title: 'Apple Handoff' },
          { slug: 'router/advanced/navigation-transitions', title: '导航过渡' },
          { slug: 'router/advanced/react-activity', title: 'React Activity' },
          { slug: 'router/advanced/custom-tabs', title: '自定义标签页' },
          { slug: 'router/advanced/custom-navigators', title: '自定义导航器' },
          { slug: 'router/advanced/stack-toolbar', title: '堆栈工具栏' },
          { slug: 'router/advanced/zoom-transition', title: '缩放过渡' },
        ],
      },
      { slug: 'router/error-handling', title: '错误处理' },
      {
        title: '参考',
        items: [
          { slug: 'router/reference/url-parameters', title: 'URL 参数' },
          { slug: 'router/reference/color', title: '颜色' },
          { slug: 'router/reference/sitemap', title: '站点地图' },
          { slug: 'router/reference/redirects', title: '重定向' },
          { slug: 'router/reference/link-preview', title: '链接预览' },
          { slug: 'router/reference/typed-routes', title: '类型化路由' },
          { slug: 'router/reference/screen-tracking', title: '页面追踪' },
          { slug: 'router/reference/src-directory', title: 'src 目录' },
          { slug: 'router/reference/testing', title: '测试' },
          { slug: 'router/reference/troubleshooting', title: '疑难排查' },
          { slug: 'router/reference/reserved-paths', title: '保留路径' },
        ],
      },
      {
        title: '迁移',
        items: [
          { slug: 'router/migrate/from-react-navigation', title: '从 React Navigation 迁移' },
          { slug: 'router/migrate/from-expo-webpack', title: '从 Expo Webpack 迁移' },
          { slug: 'router/migrate/sdk-55-to-56', title: 'SDK 55 到 56' },
          { slug: 'router/migrate/sdk-57-to-58', title: 'SDK 57 到 58' },
        ],
      },
      {
        title: 'Web 支持',
        items: [
          { slug: 'router/web/api-routes', title: 'API 路由' },
          { slug: 'router/web/data-loaders', title: '数据加载器' },
          { slug: 'router/web/middleware', title: '中间件' },
          { slug: 'router/web/server-headers', title: '服务端请求头' },
          { slug: 'router/web/static-rendering', title: '静态渲染' },
          { slug: 'router/web/server-rendering', title: '服务端渲染' },
          { slug: 'router/web/async-routes', title: '异步路由' },
        ],
      },
    ],
  },

  {
    section: 'EAS',
    items: [
      { slug: 'eas', title: 'EAS 简介' },
      { slug: 'eas/cli', title: 'EAS CLI' },
      { slug: 'eas/json', title: 'eas.json' },
      { slug: 'eas/webhooks', title: 'Webhooks' },
      {
        title: '环境变量',
        items: [
          { slug: 'eas/environment-variables/manage', title: '管理' },
          { slug: 'eas/environment-variables/usage', title: '使用' },
          { slug: 'eas/environment-variables/without-eas', title: '不使用 EAS' },
          { slug: 'eas/environment-variables/faq', title: '常见问题' },
        ],
      },
      {
        title: '构建',
        items: [
          { slug: 'build/introduction', title: '简介' },
          { slug: 'build/setup', title: '设置' },
          { slug: 'build/eas-json', title: 'eas.json 配置' },
          { slug: 'build/internal-distribution', title: '内部分发' },
          { slug: 'build/automate-submissions', title: '自动提交' },
          { slug: 'build/updates', title: '更新' },
          { slug: 'build/building-on-ci', title: '在 CI 上构建' },
          { slug: 'build/building-from-github', title: '从 GitHub 构建' },
          { slug: 'build/orbit', title: 'Orbit' },
        ],
      },
      {
        title: '构建参考',
        items: [
          { slug: 'build-reference/npm-hooks', title: 'npm Hooks' },
          { slug: 'build-reference/private-npm-packages', title: '私有 npm 包' },
          { slug: 'build-reference/git-submodules', title: 'Git 子模块' },
          { slug: 'build-reference/npm-cache-with-yarn', title: 'Yarn npm 缓存' },
          { slug: 'build-reference/build-with-monorepos', title: 'Monorepo 构建' },
          { slug: 'build-reference/apk', title: 'APK' },
          { slug: 'build-reference/simulators', title: '模拟器' },
          { slug: 'build-reference/app-versions', title: '应用版本' },
          { slug: 'build-reference/troubleshooting', title: '疑难排查' },
          { slug: 'build-reference/variants', title: '变体' },
          { slug: 'build-reference/ios-capabilities', title: 'iOS 能力' },
          { slug: 'build-reference/local-builds', title: '本地构建' },
          { slug: 'build-reference/caching', title: '缓存' },
          { slug: 'build-reference/android-builds', title: 'Android 构建' },
          { slug: 'build-reference/ios-builds', title: 'iOS 构建' },
          { slug: 'build-reference/build-configuration', title: '构建配置' },
          { slug: 'build-reference/infrastructure', title: '基础设施' },
          { slug: 'build-reference/app-extensions', title: '应用扩展' },
          { slug: 'build-reference/easignore', title: '.easignore' },
          { slug: 'build-reference/npx-testflight', title: 'npx testflight' },
          { slug: 'build-reference/repack', title: 'Re.Pack' },
          { slug: 'build-reference/limitations', title: '限制' },
        ],
      },
      {
        title: '提交',
        items: [
          { slug: 'submit/android', title: 'Android' },
          { slug: 'submit/ios', title: 'iOS' },
          { slug: 'submit/testflight', title: 'TestFlight' },
          { slug: 'submit/android-manual', title: 'Android 手动提交' },
          { slug: 'submit/ios-manual', title: 'iOS 手动提交' },
          { slug: 'submit/eas-json', title: 'eas.json' },
        ],
      },
      {
        title: '更新 (EAS Update)',
        items: [
          { slug: 'eas-update/introduction', title: '简介' },
          { slug: 'eas-update/getting-started', title: '快速开始' },
          { slug: 'eas-update/preview', title: '预览' },
          { slug: 'eas-update/channel-surfing', title: '频道切换' },
          { slug: 'eas-update/override', title: '覆盖' },
          { slug: 'eas-update/expo-dev-client', title: '开发客户端' },
          { slug: 'eas-update/github-actions', title: 'GitHub Actions' },
          { slug: 'eas-update/deployment', title: '部署' },
          { slug: 'eas-update/download-updates', title: '下载更新' },
          { slug: 'eas-update/rollouts', title: '灰度发布' },
          { slug: 'eas-update/rollbacks', title: '回滚' },
          { slug: 'eas-update/bundle-diffing', title: '增量对比' },
          { slug: 'eas-update/optimize-assets', title: '优化资源' },
          { slug: 'eas-update/deployment-patterns', title: '部署模式' },
          { slug: 'eas-update/how-it-works', title: '工作原理' },
          { slug: 'eas-update/eas-cli', title: 'EAS CLI' },
          { slug: 'eas-update/runtime-versions', title: '运行时版本' },
          { slug: 'eas-update/debug', title: '调试' },
          { slug: 'eas-update/error-recovery', title: '错误恢复' },
          { slug: 'eas-update/code-signing', title: '代码签名' },
          { slug: 'eas-update/asset-selection', title: '资源选择' },
          { slug: 'eas-update/standalone-service', title: '独立服务' },
          { slug: 'eas-update/request-proxying', title: '请求代理' },
          { slug: 'eas-update/codepush', title: '从 CodePush 迁移' },
          { slug: 'eas-update/migrate-from-classic-updates', title: '从经典更新迁移' },
          { slug: 'eas-update/trace-update-id-expo-dashboard', title: '在仪表盘追踪更新 ID' },
          { slug: 'eas-update/estimate-bandwidth', title: '估算带宽' },
          { slug: 'eas-update/integration-in-existing-native-apps', title: '集成到现有原生应用' },
        ],
      },
      {
        title: '分发',
        items: [
          { slug: 'distribution/introduction', title: '简介' },
          { slug: 'distribution/app-stores', title: '应用商店' },
          { slug: 'distribution/app-transfers', title: '应用转让' },
          { slug: 'distribution/app-size', title: '应用大小' },
        ],
      },
      {
        title: '应用签名',
        items: [
          { slug: 'app-signing/app-credentials', title: '应用凭据' },
          { slug: 'app-signing/managed-credentials', title: '托管凭据' },
          { slug: 'app-signing/local-credentials', title: '本地凭据' },
          { slug: 'app-signing/existing-credentials', title: '现有凭据' },
          { slug: 'app-signing/syncing-credentials', title: '同步凭据' },
          { slug: 'app-signing/security', title: '安全' },
          { slug: 'app-signing/apple-developer-program-roles-and-permissions', title: 'Apple 开发者计划角色与权限' },
        ],
      },
      {
        title: '自定义构建',
        items: [
          { slug: 'custom-builds/get-started', title: '快速开始' },
          { slug: 'custom-builds/schema', title: '模式 (Schema)' },
          { slug: 'custom-builds/functions', title: '函数' },
        ],
      },
      {
        title: '计费',
        items: [
          { slug: 'billing/overview', title: '概览' },
          { slug: 'billing/plans', title: '套餐' },
          { slug: 'billing/manage', title: '管理' },
          { slug: 'billing/invoices-and-receipts', title: '发票与收据' },
          { slug: 'billing/usage-based-pricing', title: '按量计费' },
          { slug: 'billing/faq', title: '常见问题' },
        ],
      },
      {
        title: '账户',
        items: [
          { slug: 'accounts/account-types', title: '账户类型' },
          { slug: 'accounts/two-factor', title: '两步验证' },
          { slug: 'accounts/programmatic-access', title: '程序化访问' },
          { slug: 'accounts/sso', title: '单点登录 (SSO)' },
          { slug: 'accounts/audit-logs', title: '审计日志' },
        ],
      },
      {
        title: 'EAS 托管 (Hosting)',
        items: [
          { slug: 'eas/hosting/introduction', title: '简介' },
          { slug: 'eas/hosting/get-started', title: '快速开始' },
          { slug: 'eas/hosting/deployments-and-aliases', title: '部署与别名' },
          { slug: 'eas/hosting/custom-domain', title: '自定义域名' },
          { slug: 'eas/hosting/api-routes', title: 'API 路由' },
          { slug: 'eas/hosting/workflows', title: '工作流' },
          { slug: 'eas/hosting/reference/caching', title: '缓存' },
          { slug: 'eas/hosting/reference/responses-and-headers', title: '响应与请求头' },
          { slug: 'eas/hosting/reference/worker-runtime', title: 'Worker 运行时' },
        ],
      },
      {
        title: '元数据',
        items: [
          { slug: 'eas/metadata/getting-started', title: '快速开始' },
          { slug: 'eas/metadata/config', title: '配置' },
          { slug: 'eas/metadata/schema', title: '模式 (Schema)' },
        ],
      },
      {
        title: '可观测性 (Observe)',
        items: [
          { slug: 'eas/observe/introduction', title: '简介' },
          { slug: 'eas/observe/get-started', title: '快速开始' },
          { slug: 'eas/observe/dashboard', title: '仪表盘' },
          { slug: 'eas/observe/eas-cli', title: 'EAS CLI' },
          { slug: 'eas/observe/eas-update', title: 'EAS Update 集成' },
          { slug: 'eas/observe/events', title: '事件' },
          { slug: 'eas/observe/errors', title: '错误' },
          { slug: 'eas/observe/configuration', title: '配置' },
          { slug: 'eas/observe/integrations/expo-router', title: 'Expo Router 集成' },
          { slug: 'eas/observe/integrations/react-navigation', title: 'React Navigation 集成' },
          { slug: 'eas/observe/integrations/expo-image', title: 'Expo Image 集成' },
          { slug: 'eas/observe/integrations/third-party', title: '第三方集成' },
          { slug: 'eas/observe/reference/metrics', title: '指标' },
          { slug: 'eas/observe/reference/client-id', title: '客户端 ID' },
          { slug: 'eas/observe/reference/troubleshooting', title: '疑难排查' },
        ],
      },
      {
        title: 'EAS 洞察 (Insights)',
        items: [
          { slug: 'eas-insights/introduction', title: '简介' },
          { slug: 'eas-insights/app-usage', title: '应用使用' },
          { slug: 'eas-insights/workflows', title: '工作流' },
          { slug: 'eas-insights/maestro', title: 'Maestro' },
          { slug: 'eas-insights/eas-cli', title: 'EAS CLI' },
        ],
      },
      {
        title: 'EAS 工作流',
        items: [
          { slug: 'eas/workflows/introduction', title: '简介' },
          { slug: 'eas/workflows/get-started', title: '快速开始' },
          { slug: 'eas/workflows/pre-packaged-jobs', title: '预打包任务' },
          { slug: 'eas/workflows/syntax', title: '语法' },
          { slug: 'eas/workflows/custom-functions', title: '自定义函数' },
          { slug: 'eas/workflows/environment', title: '环境' },
          { slug: 'eas/workflows/automating-eas-cli', title: '自动化 EAS CLI' },
          { slug: 'eas/workflows/rest-api', title: 'REST API' },
          { slug: 'eas/workflows/troubleshooting', title: '疑难排查' },
          { slug: 'eas/workflows/limitations', title: '限制' },
          { slug: 'eas/workflows/examples/introduction', title: '示例' },
          { slug: 'eas/workflows/examples/create-development-builds', title: '创建开发构建' },
          { slug: 'eas/workflows/examples/publish-preview-update', title: '发布预览更新' },
          { slug: 'eas/workflows/examples/branch-cleanup', title: '分支清理' },
          { slug: 'eas/workflows/examples/deploy-to-production', title: '部署到生产' },
          { slug: 'eas/workflows/examples/e2e-tests', title: 'E2E 测试' },
        ],
      },
    ],
  },

  {
    section: '工作流',
    items: [
      { slug: 'workflow/overview', title: '概览' },
      { slug: 'workflow/configuration', title: '配置' },
      { slug: 'workflow/continuous-native-generation', title: '持续原生代码生成 (CNG)' },
      { slug: 'workflow/using-libraries', title: '使用第三方库' },
      { slug: 'workflow/customizing', title: '自定义原生项目' },
      { slug: 'workflow/web', title: 'Web' },
      { slug: 'workflow/logging', title: '日志' },
      { slug: 'workflow/development-mode', title: '开发模式' },
      { slug: 'workflow/common-development-errors', title: '常见开发错误' },
      { slug: 'workflow/android-studio-emulator', title: 'Android Studio 模拟器' },
      { slug: 'workflow/ios-simulator', title: 'iOS 模拟器' },
      { slug: 'workflow/upgrading-expo-sdk-walkthrough', title: '升级 Expo SDK 演练' },
    ],
  },

  {
    section: '教程',
    items: [
      { slug: 'tutorial/introduction', title: '教程简介' },
      { slug: 'tutorial/overview', title: '教程概览' },
      { slug: 'tutorial/create-your-first-app', title: '创建你的第一个应用' },
      { slug: 'tutorial/build-a-screen', title: '构建界面' },
      { slug: 'tutorial/add-navigation', title: '添加导航' },
      { slug: 'tutorial/create-a-modal', title: '创建模态框' },
      { slug: 'tutorial/gestures', title: '手势' },
      { slug: 'tutorial/image-picker', title: '图片选择器' },
      { slug: 'tutorial/screenshot', title: '截图' },
      { slug: 'tutorial/platform-differences', title: '平台差异' },
      { slug: 'tutorial/configuration', title: '配置' },
      { slug: 'tutorial/follow-up', title: '后续步骤' },
      {
        title: '使用 AI 构建',
        items: [
          { slug: 'tutorial/build-with-ai/introduction', title: '简介' },
          { slug: 'tutorial/build-with-ai/set-up-your-tools', title: '设置工具' },
          { slug: 'tutorial/build-with-ai/create-your-first-app', title: '创建第一个应用' },
          { slug: 'tutorial/build-with-ai/build-the-home-screen', title: '构建首页' },
          { slug: 'tutorial/build-with-ai/add-stickers', title: '添加贴纸' },
          { slug: 'tutorial/build-with-ai/save-your-creation', title: '保存作品' },
          { slug: 'tutorial/build-with-ai/finishing-touches', title: '收尾' },
        ],
      },
      {
        title: 'EAS 教程',
        items: [
          { slug: 'tutorial/eas/introduction', title: '简介' },
          { slug: 'tutorial/eas/configure-development-build', title: '配置开发构建' },
          { slug: 'tutorial/eas/android-development-build', title: 'Android 开发构建' },
          { slug: 'tutorial/eas/ios-development-build-for-simulators', title: 'iOS 模拟器开发构建' },
          { slug: 'tutorial/eas/ios-development-build-for-devices', title: 'iOS 设备开发构建' },
          { slug: 'tutorial/eas/multiple-app-variants', title: '多个应用变体' },
          { slug: 'tutorial/eas/internal-distribution-builds', title: '内部分发构建' },
          { slug: 'tutorial/eas/manage-app-versions', title: '管理应用版本' },
          { slug: 'tutorial/eas/android-production-build', title: 'Android 生产构建' },
          { slug: 'tutorial/eas/ios-production-build', title: 'iOS 生产构建' },
          { slug: 'tutorial/eas/team-development', title: '团队开发' },
          { slug: 'tutorial/eas/using-github', title: '使用 GitHub' },
          { slug: 'tutorial/eas/next-steps', title: '下一步' },
        ],
      },
      {
        title: 'CI/CD 教程',
        items: [
          { slug: 'tutorial/cicd/introduction', title: '简介' },
          { slug: 'tutorial/cicd/first-workflow', title: '第一个工作流' },
          { slug: 'tutorial/cicd/development-builds', title: '开发构建' },
          { slug: 'tutorial/cicd/preview-builds', title: '预览构建' },
          { slug: 'tutorial/cicd/e2e-tests', title: 'E2E 测试' },
          { slug: 'tutorial/cicd/production', title: '生产环境' },
          { slug: 'tutorial/cicd/tag-based-releases', title: '基于标签发布' },
          { slug: 'tutorial/cicd/web-deployments', title: 'Web 部署' },
          { slug: 'tutorial/cicd/next-steps', title: '下一步' },
        ],
      },
    ],
  },

  {
    section: '更多',
    items: [
      { slug: 'additional-resources', title: '更多资源' },
      { slug: 'core-concepts', title: '核心概念' },
      { slug: 'faq', title: '常见问题' },
      {
        title: 'AI Agent',
        items: [
          { slug: 'agents', title: '概览' },
          { slug: 'agents/claude', title: 'Claude Code' },
          { slug: 'agents/codex', title: 'Codex' },
          { slug: 'agents/cursor', title: 'Cursor' },
          { slug: 'agents/argent', title: 'Argent' },
          { slug: 'agents/agent-device', title: 'Agent 设备' },
        ],
      },
      { slug: 'skills', title: 'Expo Skills' },
      { slug: 'mcp', title: 'Expo MCP Server' },
      {
        title: '裸工作流 (Bare)',
        items: [
          { slug: 'bare/overview', title: '概览' },
          { slug: 'bare/installing-expo-modules', title: '安装 Expo 模块' },
          { slug: 'bare/using-expo-cli', title: '使用 Expo CLI' },
          { slug: 'bare/installing-updates', title: '安装更新' },
          { slug: 'bare/install-dev-builds-in-bare', title: '安装开发构建' },
          { slug: 'bare/upgrade', title: '升级' },
        ],
      },
      {
        title: '混合开发 (Brownfield)',
        items: [
          { slug: 'brownfield/overview', title: '概览' },
          { slug: 'brownfield/isolated-approach', title: '隔离方案' },
          { slug: 'brownfield/integrated-approach', title: '集成方案' },
          { slug: 'brownfield/lifecycle-listeners', title: '生命周期监听器' },
        ],
      },
      { slug: 'monitoring/services', title: '监控服务' },
      {
        title: '工具参考',
        items: [
          { slug: 'more/expo-cli', title: 'Expo CLI' },
          { slug: 'more/create-expo', title: 'create-expo-app' },
          { slug: 'more/create-expo-module', title: 'create-expo-module' },
          { slug: 'more/qr-codes', title: '二维码 (qr.expo.dev)' },
          { slug: 'more/release-statuses', title: '发布状态' },
          { slug: 'more/glossary-of-terms', title: '术语表' },
        ],
      },
    ],
  },
]
